// docs/src/js/App.vue
<template>
  <div>
    <Header/>
    <ul>
      <li><router-link to="/">Home</router-link></li>
      <li><router-link to="/about">About</router-link></li>
    </ul>

    <hr>
    <router-view/>
  </div>
</template>

<script>
import Header from 'Header.vue'

export default {
  components: { Header }
}
</script>

<style lang="scss" scoped>
.app {
    color: #333;
}
</style>

// docs/src/js/app.jsx
import React from 'react'
import PropTypes from 'prop-types'
import { Route, Link } from 'react-router-dom'

import Header from '../components/Header'
import Home from '../components/Home'
import About from '../components/About'

function App ({name, actions}) {
  return <div className='app'>
    <Header name={name} actions={actions} />
    <ul>
      <li><Link to='/'>Home</Link></li>
      <li><Link to='/about'>About</Link></li>
    </ul>

    <hr />
    <Route exact path='/' component={Home} />
    <Route path='/about' component={About} />
  </div>
}

App.propTypes = {
  name: PropTypes.string.isRequired,
  actions: PropTypes.object.isRequired
}

export default App
